version: 2
updates:
- package-ecosystem: npm
  directory: "/Web/ClientApp"
  schedule:
    interval: daily
    time: "01:30"
    timezone: Asia/Tehran
  open-pull-requests-limit: 99
  target-branch: dev
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "01:30"
    timezone: Asia/Tehran
  open-pull-requests-limit: 99
  target-branch: dev